version: '3'
services:
  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:${SOFTWARE_VERSION_TAG}
    container_name: keycloak
    restart: always
    env_file:
      - .env
    ports:
      - 172.17.0.1:8080:8080
      - $NEBULA_IP:7800:7800
    environment:
      INFINISPAN_EXTERNAL_IP: $NEBULA_IP
      JAVA_OPTS: -XX:MaxRAMPercentage=90 -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+DisableExplicitGC -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djgroups.external_addr=$NEBULA_IP
      JGROUPS_DISCOVERY_PROPERTIES: remove_all_data_on_view_change=true,clear_table_on_view_change=true,datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500,initialize_sql=\"CREATE TABLE IF NOT EXISTS JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name));\"
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      KC_CACHE_CONFIG_FILE: cache-ispn-jdbc-ping.xml
      KC_DB: $DATABASE
      KC_DB_PASSWORD: $DATABASE_PASS
      KC_DB_POOL_MIN_SIZE: 0
      KC_DB_SCHEMA: $DATABASE_SCHEMA
      KC_DB_URL_DATABASE: $DATABASE_NAME
      KC_DB_URL_HOST: $DATABASE_HOST
      KC_DB_URL_PORT: $DATABASE_PORT
      KC_DB_URL_PROPERTIES: ''
      KC_DB_USERNAME: $DATABASE_USER
      KC_FEATURES: preview,admin2
      KC_HEALTH_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_HTTP_RELATIVE_PATH: /
      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: 'true'
      KC_PROXY: 'edge'
      KC_SPI_THEME_WELCOME_THEME: phasetwo
      KC_TRANSACTION_JTA_ENABLED: 'false'
      KC_TRANSACTION_XA_ENABLED: 'false'
      KEYCLOAK_ADMIN: $KEYCLOAK_USER
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_PASS
      PROXY_ADDRESS_FORWARDING: 'true'
    volumes:
      - ./cache-ispn-jdbc-ping.xml:/opt/keycloak/conf/cache-ispn-jdbc-ping.xml
      - ./keycloak_data:/keycloak_data:rw
    networks:
      - keycloak-network
    entrypoint: /opt/keycloak/bin/kc.sh --verbose start --spi-email-template-provider=freemarker-plus-mustache --spi-email-template-freemarker-plus-mustache-enabled=true

networks:
  keycloak-network:
    driver: bridge
