version: '3.3'
services:
  keycloak:
    container_name: keycloak
    user: 0:0
    image: elestio/keycloak:${SOFTWARE_VERSION_TAG}
    restart: always
    entrypoint: '/opt/keycloak/bin/kc.sh start'
    volumes:
      - ./providers:/opt/keycloak/providers
      - ./themes:/opt/keycloak/themes
      - ./cache-ispn-tcp-ping.xml:/opt/keycloak/conf/cache-ispn-tcp-ping.xml
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: $ADMIN_LOGIN
      KEYCLOAK_ADMIN_PASSWORD: $SOFTWARE_PASSWORD
      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: 'true'
      JAVA_OPTS: -XX:MaxRAMPercentage=75.0
      KC_CACHE_CONFIG_FILE: cache-ispn-tcp-ping.xml
      KC_EXTERNAL_ADDR: $NEBULA_IP
      KC_BIND_ADDR: keycloak
      KC_BIND_PORT: 7800
      KC_INITIAL_HOSTS: $NODES_HOSTS
    ports:
      - 172.17.0.1:8080:8080
      - $NEBULA_IP:7800:7800
